_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "swin_tiny_patch4_window7_224_d2.pth"
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_retinanet_swint_fpn_backbone"
  SWINT:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
