# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    types: [ submitted ]
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
  # This workflow contains a single job called "build"
jobs:
  docker-test:
    # The type of runner that the job will run on
    #if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    # docker image
#    container:
#      image: mkl-spams_tf2.3_torch1.7.1_cuda10.1_cudnn7_ubuntu16.04:solov2 
    services:
      registry:
        image: mkl-spams_tf2.3_torch1.7.1_cuda10.1_cudnn7_ubuntu16.04:solov2 
        ports:
          - 8992:8992
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

#      - name: log node version
#        run: node -v
#      - name: Step with docker
#        uses: docker://node:12.14.1-alpine3.10 #このステップだけで起動するコンテナイメージ
#        with:
#          entrypoint: '/bin/echo' #コンテナ起動時にechoコマンドを実行
#          args: 'Hello World' #echoコマンドの引数
#      - name: Log node version
#        uses: docker://node:12.14.1-alpine3.10 
#        with:
#          entrypoint: '/usr/local/bin/node' #コンテナ起動時にnodeコマンドを実行
#          args: -v #nodeコマンドの引数(バージョン確認)
